### ISSUE TITLE
Need `--account-contract` flag when importing `IAccount` 

### ISSUE THREAD

**Issue by pscott** [OpenZeppelin/cairo-contracts#328] opened 2022-05-20 12:39 UTC
`IAccount` exopses the `__execute__` function which gets the cairo-compiler to yell and error like this:
```
Only account contracts may have a function named "__execute__". Use --account-contract flag.

        Failed
 ```

Unfortunately this means I can't write a contract that includes `IAccount` without adding the `--account-contract` flag (which is plain wrong because I'm NOT writing an account contract but simply interacting with one!).

Not sure OZ can do anything about it, I think we need to address this to the StarkWare team but just putting it out there :)

**Comment by martriay** [comment] 2022-05-20 22:44
Agree with this. I don't think this flag makes much sense cc/@bbrandtom

**Comment by ilyalesokhin-starkware** [comment] 2022-05-25 11:09
I was unable to reproduce the issue.

What do you mean by `IAccount exopses the __execute__`?W
IAccount only defines an interface, it does not define any `@external` entry point.

**Comment by pscott** [comment] 2022-05-25 11:17
@ilyalesokhin-starkware thanks for having a look at this!

Here's a minimal working (failing) example. I'm trying to compile it with `0.8.2.1` and it's giving me the error I mentioned in the OP.

https://gist.github.com/pscott/aa99849a1e1b53f2eaed3f71de642e8e

**Comment by ilyalesokhin-starkware** [comment] 2022-05-25 11:43
The example compiles on my machine.

Are you sure you didn't change one of the imported files to include an `__execute__` entrypoint?

**Comment by pscott** [comment] 2022-05-25 11:49
Interesting... I'm using `0.1.0` of `openzeppelin-cairo-contracts` dependency. Are you running this version too? (installed via `pip3 install openzeppelin-cairo-contracts`)

I have not added any `__execute__` entrypoint.

Maybe someone else can reproduce?

**Comment by pscott** [comment] 2022-05-25 11:53
Also it should be noted that I'm using the [`starknet hardhat plugin`](https://github.com/Shard-Labs/starknet-hardhat-plugin) and running `npx hardhat starknet-compile` in order to compile.

**Comment by ilyalesokhin-starkware** [comment] 2022-05-26 07:55
This is related to the #291 and it's already fixed in the main branch of openzeppelin-cairo-contracts.

openzeppelin-cairo-contracts v0.1.0 is broken.

**Comment by pscott** [comment] 2022-05-26 09:21
All right so I guess problem solved! So I guess you testing with a local clone of the OZ repo?

**Comment by ilyalesokhin-starkware** [comment] 2022-05-26 09:39
Your guess is correct, my first attempt to reproduce the issue failed as I fetched the most recent master from the OZ repo.

**Comment by martriay** [comment] 2022-05-26 16:11
> All right so I guess problem solved! So I guess you testing with a local clone of the OZ repo?
> 
> @martriay @andrew-fleming do you think OZ could issue a `0.1.1` while waiting for `0.2.0`? Would be really nice to be able to use `Account`s right now :D

No, we're really close to 0.2.0 and it would be a ton of work to cherrypick non-breaking changes to release 0.1.0

**Comment by bbrandtom** [comment] 2022-05-30 06:02
@martriay why do you think the flag is problematic? Why an 'account' directive will be better?

**Comment by martriay** [comment] 2022-06-15 03:02
> @martriay why do you think the flag is problematic? Why an 'account' directive will be better?

Because you can't just compile all the contracts on a project, and there's no easy nor reliable way to identify them. It's also unclear to me the added value.

A directive I would assume serves the same purpose you intend to give it, without interfering with compilation/tooling and if anything, providing a way for tooling to circumvent the issue/

**Comment by martriay** [comment] 2023-02-16 21:06
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.

**Closed by martriay** 2023-02-16 21:06 UTC
