### ISSUE TITLE
Update openzeppelin wizard code to latest cairo syntax

### ISSUE THREAD

**Issue by Nonnyjoe** [OpenZeppelin/cairo-contracts#798] opened 2023-10-25 20:39 UTC
The current Openzeppelin wizard generates cairo contracts using the old cairo syntax, and this might be an issue for new cairo developers who do not understand the previous cairo syntax. It'll be nice to update it to the latest cairo syntax.

**Comment by martriay** [comment] 2023-10-25 21:02
#wizard

**Comment by martriay** [comment] 2023-10-25 21:04
Thanks, this was planned already. Closing as duplicate of https://github.com/OpenZeppelin/cairo-contracts/issues/747.

**Closed by martriay** 2023-10-25 21:04 UTC
