### ISSUE TITLE
Cairo 1 version of the Deployer contract

### ISSUE THREAD

**Issue by antazoey** [OpenZeppelin/cairo-contracts#609] opened 2023-04-18 18:38 UTC
**🧐 Motivation**

* Would be easier to use tooling meant for Cairo 1 to interact with the deployer (ABI conflicts currently).
* Will help make a custom deployer.

**📝 Details**

Similar to the other migration work.

**Comment by antazoey** [comment] 2023-04-18 18:54
I would like to try and implement this though I am not well-versed in Cairo.
What I have so far:

```rust
#[contract]
mod UniversalDeployer {
    use array::ArrayTrait;
    use starknet::ContractAddress;
    use starknet::class_hash::ClassHash;
    use starknet::get_caller_address;
    use starknet::syscalls::deploy_syscall;

    #[event]
    fn ContractDeployed(
        address: ContractAddress,
        deployer: ContractAddress,
        unique: bool,
        class_hash: ClassHash,
        calldata: ArrayTrait,
        salt: felt252
    ) {
    }

    #[external]
    fn deploy_contract(
        class_hash: ClassHash,
        salt: felt252,
        unique: bool,
        calldata: ArrayTrait
    ) {
        let deployer = get_caller_address();

        let mut _salt = 0;
        let mut from_zero = false;

        if unique {
            _salt = hash2(deployer, salt);
        } else {
            _salt = salt;
            from_zero = true;
        }

        deploy_syscall(
            class_hash, _salt, calldata.span(), from_zero
        );

    }   
}
```

**Comment by andrew-fleming** [comment] 2023-04-18 23:36
Thanks, @antazoey! I did start this already, but I'll draft a PR with what I have. It still needs work and tests, but a review is welcomed :)

**Comment by martriay** [comment] 2023-04-26 13:54
Closed as duplicate of https://github.com/OpenZeppelin/cairo-contracts/issues/552. If you think this is a mistake, free to open a new issue.

**Closed by martriay** 2023-04-26 13:54 UTC
