### ISSUE TITLE
Governance package in Cairo

### ISSUE THREAD

**Issue by 0xAurelou** [OpenZeppelin/cairo-contracts#424] opened 2022-08-09 15:56 UTC
**🧐 Motivation**
Governance is a must have, we need it in Cairo guys.

**📝 Details**
https://docs.openzeppelin.com/contracts/4.x/governance

**Comment by martriay** [comment] 2022-08-09 19:57
Agree! But closing this issue since it's a duplicate of #294.

**Closed by martriay** 2022-08-09 19:57 UTC
