### ISSUE TITLE
Can I modify the token_uri? The output felt252 does not meet my requirements。

### ISSUE THREAD

**Issue by ArsEarth** [OpenZeppelin/cairo-contracts#903] opened 2024-02-08 08:10 UTC
**🧐 Motivation**

**📝 Details**

**Comment by martriay** [comment] 2024-02-09 01:25
Closing as duplicate of https://github.com/OpenZeppelin/cairo-contracts/issues/886

**Closed by martriay** 2024-02-09 01:25 UTC
