### ISSUE TITLE
Can't compile account with `scarb 2.5.0`, `snforge 0.16.0`, `openzeppelin 0.8.1`

### ISSUE THREAD

**Issue by delaaxe** [OpenZeppelin/cairo-contracts#871] opened 2024-01-29 11:36 UTC
<img width="844" alt="Screenshot 2024-01-29 at 11 33 32" src="https://github.com/OpenZeppelin/cairo-contracts/assets/1091900/0a0e0e23-b8b6-472e-97cc-59b99bda7b22">

Is there a workaround or something with my own env?

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by martriay** [comment] 2024-01-30 00:15
Hey there! The problem is that v0.8.1 is intended to work with Cairo 2.4.1 as specified in its [Scarb.toml](https://github.com/OpenZeppelin/cairo-contracts/blob/release-v0.8.1/Scarb.toml) file. We have an [open issue](https://github.com/OpenZeppelin/cairo-contracts/issues/877) to support Cairo 2.5.0. In the meantime, you could [manually update the account](https://github.com/OpenZeppelin/cairo-contracts/pull/870/files) to work with Cairo 2.5.0 at your own risk. Make sure to properly review and test any modified code.

**Comment by delaaxe** [comment] 2024-01-30 10:17
we don't actually use the account, we'd juste like to import the ERC20 definitions (which we actually can't use anymore since the decimals are hardcoded to 18, so we had to copy paste files)

**Comment by martriay** [comment] 2024-01-30 14:37
We have a guide in our documentation on [how to customize decimals](https://docs.openzeppelin.com/contracts-cairo/0.8.1/erc20#customizing_decimals).

**Comment by martriay** [comment] 2024-01-31 18:31
Closing as duplicate of #877

**Closed** 2024-01-31 18:31 UTC
